### ISSUE TITLE
Convert the static guides to multipane

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#177]
After multipane design has been successfully tested with some guides, and all the feedback issues are resolved. This issue is to work out the plan to convert all the static guides to multipane design.

**Comment by gkwan-ibm** [comment]
kick off on today

**Comment by gkwan-ibm** [comment]
- Working on 4 guides: CDI, JWT, Docker, Getting Started

**Comment by justineechen** [comment]
### Checklist for multipane conversion
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [ ] Hotspots actually point to the correct lines
- [ ] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present

**In the README.adoc:**
- [ ] Tags in the front matter are correct
     - [ ] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`
     - [ ] seo tag?

**In other files:**
- [ ] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
     - [ ] start directory
     - [ ] finish directory
- [ ] Files are formatted correctly
- [ ] .travis.yaml file is updated accordingly

**Comment by gkwan-ibm** [comment]
- completed the changes for 4 guides: CDI, JWT, Docker, Getting Started
- will review them on today
- will start another batch on next

**Comment by gkwan-ibm** [comment]
- still reviewing the 4 guides

**Comment by evelinec** [comment]
- 2 guides completed, docker and cdi 
- almost done: getting started, JWT
- working on: FT, Rest-Intro and 2 other new ones

**Comment by gkwan-ibm** [comment]
- found issues on getting started and JWT
- working angularAS, fallback, kube intro, restful
- found issue on fallback

**Comment by gkwan-ibm** [comment]
- reviewing: Rest-intro, Fallback, JWT, Getting-started and AngularJS. 
- Getting-started and JWT should be almost finished review. 
- starting to convert Maven-intro

**Comment by gkwan-ibm** [comment]
- Done
  - Getting-started, Fallback 
- Almost done
  - JWT
  - AngularJS 
  - Rest-intro
- Review
  - Maven-intro
- Will start another 2 guides

**Comment by evelinec** [comment]
- all of the guides are converted and under review
- status board shows 21 guide items, Justine to look into the 4 missing
- some guides have blocker issues (2 new), will work with Steven
- continue working with the rest of the team till end of the week

**Comment by gkwan-ibm** [comment]
- to complete post-review today
- will start next round update
   - guide author
   - update to master
   - consistent mvn instructions
   - stop server
   - or more

**Comment by gkwan-ibm** [comment]
- tried to run auto test for all guides
  - some of them failed
- working in the test for AngularJS guide
- looking through Docker and CDI guides test coverage
- Some issues is captured at https://ibm.ent.box.com/notes/381619770492?s=3fnhxod4nnrx0d8lfrojsxni5g8mkvhq

**Comment by gkwan-ibm** [comment]
- removed the Contribution sections for all guides
- AngularJS guide test will be reviewed
- need to check the  dependencies order for all guides
   - features
   - test
   - jdk 9,10

**Comment by gkwan-ibm** [comment]
- AngularJS, Docker, Getting start guides auto test coverage revisit completed
- fixing the automation failures for Kube Intro, Kube Health, Opentracing
- working on the dependencies

**Comment by gkwan-ibm** [comment]
- need to discuss with Jay for the action arrow behavior change

**Comment by evelinec** [comment]
- Jay will determine how the action arrow will look, and update the guides
- work on 2 tasks that are related jdk11
- continue to follow up with Steven on the remaining issues

**Comment by evelinec** [comment]
- still pending on Jay on the action arrow design (target?)
- reviewing the all the open issues on the guides and closing them
- new issues from new updates.. ie, multiline hotspot
- work on 2 tasks that are related jdk11

**Comment by evelinec** [comment]
- action arrow design is ready this morning, steven needs to implement it
- made some wording changes for the JWT guide and refreshed `user-testing` site
- put in multiline hotspot fixes in the relevant guides 
- a new high priority issue open for guides doesn't have any code for the code pane
- made the jdk11 changes for Justine's guides, and Andrew is still working on them

**Comment by evelinec** [comment]
- working on more guides requires wording changes as discussed with Jay
- completed all jdk11 changes for all guide
- more guides need the multiline hotspot fixes 
- pending on the action arrow implementation

**Comment by evelinec** [comment]
- working on the list of change discussed with Jay
- still working on more guides that need the multiline hotspot fixes
- pending on the action arrow implementation

**Comment by evelinec** [comment]
- half way through working on the list of changes discussed with Jay
- pending on the action arrow implementation

**Comment by evelinec** [comment]
- found a problem (replacing a file) while going through the changes from Jay
- pending on the action arrow implementation

**Comment by evelinec** [comment]
- pending on the action arrow implementation

**Comment by gkwan-ibm** [comment]
- will need to fix some guides for 
   - new action arrow (4 guides)
   - hotspot=*

**Comment by gkwan-ibm** [comment]
- UI will merge the long hotspot and text wrapping PR soon
- All guides were updated for the hotspot change
- Andrew and Gilbert will verify the above
- Arquillian was converted to multipane
- Istio was converted to multipane, and Justine will review it
- updating on the guide template for multipane

**Comment by gkwan-ibm** [comment]
- ready for Andrew and Gilbert to review
- working on template and instruction

**Comment by gkwan-ibm** [comment]
@andrewdes  @justineechen Put your initial (AD, JC, GK) for the guide which you are reviewing
https://qa-guides-multipane.mybluemix.net/guides/

- [ ] guide-bean-validation ()
- [ ] guide-cdi-intro ()
- [ ] guide-cors ()
- [ ] guide-docker ()
- [ ] guide-getting-started ()
- [ ] guide-gradle-intro ()
- [ ] guide-istio-intro ()
- [ ] guide-jpa-intro ()
- [ ] guide-kubernetes-intro ()
- [ ] guide-kubernetes-microprofile-config ()
- [ ] guide-kubernetes-microprofile-health ()
- [ ] guide-maven-intro ()
- [ ] guide-maven-multimodules ()
- [ ] guide-microprofile-config ()
- [ ] guide-microprofile-fallback ()
- [ ] guide-microprofile-health ()
- [ ] guide-microprofile-jwt ()
- [ ] guide-microprofile-metrics ()
- [ ] guide-microprofile-openapi ()
- [ ] guide-microprofile-opentracing ()
- [ ] guide-microprofile-rest-client ()
- [ ] guide-rest-client-angularjs ()
- [ ] guide-rest-client-java ()
- [ ] guide-rest-hateoas ()
- [ ] guide-rest-intro ()
- [ ] guide-security-intro ()

**Comment by gkwan-ibm** [comment]
- fixed the URLs
- dup "Nice Work!" was fixed by UI
- will address the issues opened by AD and GK
- AD and GK will continue to verify all guides
- target: complete the review in this week

**Comment by gkwan-ibm** [comment]
- completed the first round pre-publish test
- AD and GK will address the issues and verify the guides
