### ISSUE TITLE
Test infrastructure and process

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#205]
- [x] every good build (DHE or ArtifactFactory) - DHE only
  - [x] dashboard on Jenkins for results
- [x] 4M log limit
- [ ] Test coverage
  - [ ] verify the start directory, either
    - diff finish vs start  (#202)
    - run `mvn install` under start directory
  - [x] different JDKs (e.g. #203)
  - [x] different platforms, either
    - [x] through Jenkins, running on Travis
    - [ ] set up our own VM 
- [ ] review each guide test coverage  (otherwise, we need to do manually test for every release build)
  - improve if not enough
  - identifed
    - [ ] Getting started guide: verify the existing of jar file (https://github.com/OpenLiberty/guide-getting-started/issues/44)
    - [ ] Getting started guide: verify the docker work properly
    - [x] Gradle guide: failed by using 5.1
- Diagram/Doc/Instructions/Check list for whatever apply to the above
  - [ ] Wiki doc for daily build, docker image daily build, draft guide daily build (AD+NG)
  - [ ] Wiki doc for feature update check automation (PR+DS)

**Comment by gkwan-ibm** [comment]
- 4M log limit will be addressed by multipane
- start working on test every good build and dashboard

**Comment by gkwan-ibm** [comment]
- Need to fix the Jenkins script for 4M log limit issue
- studied the Jenkins dashboard. Look like it does not help

**Comment by gkwan-ibm** [comment]
- fixed the Jenkins script for 4M log limit issue and did some workaround
- investigating some failed guides

**Comment by gkwan-ibm** [comment]
- fixed 3 guides
- created test script for kube guides
- working on to test against artifactory
- found out that travis can test 
  - on mac and linux
  - different jdks: OpenJDK, Oracle and different versions: 8, 9, 10

**Comment by gkwan-ibm** [comment]
- fixed the  kube guide issues for running in jenkins
- understanding dhe vs artifactory
- studying dashboard for gathering data

**Comment by gkwan-ibm** [comment]
- new builds will be pushed to artifactory and then will try the automation
- working the dashboard prototype

**Comment by gkwan-ibm** [comment]
- tried travis to run automation on multi-platforms - linux and mac
- prototyped different options for dashboard

**Comment by gkwan-ibm** [comment]
- working on dashboard for Gilbert's feedback

**Comment by gkwan-ibm** [comment]
- need to map the builds with the submitted jobs
- need to improve the efficiency because now it takes 2 hours
- Mac only can run the default Oracle JDK8

**Comment by gkwan-ibm** [comment]
- auto test can run for builds in dhe
  - OSs x JDKs
- working on dashboard
- source to run the automation in the automation rep

**Comment by gkwan-ibm** [comment]
- need to address the timezone issue for testing systems
- suggest to schedule the automation as soon as ready, instead of too late

**Comment by evelinec** [comment]
Feedback to be addressed: 
- [ ] enable test on Linux and Mac with default JDK (8) — P1
- [ ] title of job: Regression test on a daily build — P1
- [ ] change build date to build level — P1.1
- [ ] build number hover info: build level, overall pass/failed — P1.2
- [ ] console log for test report: create a failure section to include links to the travis build/jobs — P2
- [ ] display build level as Jenkins build number  — P3
- [ ] console log for test report: 
	- summary: — P4
		- overall pass/failed
		- % of success
- [ ] build number hover info: if failed, calculate x% successful, x% failure — P4
- [ ] schedule daily at 12AM to schedule => schedule hourly	— P5
	- with 5 minutes delate to check builds and kick off build test right away
- [ ] run in parallel, improve performance — P6

**Comment by gkwan-ibm** [comment]
- got good result for Linux on 0109
- need to work on Mac
   - seds
   - kube guides
- test coverage, e.g.
  - Getting starte guide
  - cover all scenarios/urls described in the ReadMe
  - Missing test, e,g Angularjs guides
    - Gradle gudie to test Gradle 4.1 and 5.1

**Comment by gkwan-ibm** [comment]
- working on gradle guide 
- continue to fix issues

**Comment by evelinec** [comment]
- tested the JPA and Security-Intro automation config, tests were good
- working on the top priority defects

**Comment by gkwan-ibm** [comment]
- need to address the guides which using configuration directory instead of file
- working on gradle guide test
- currently, Eveline to monitor the daily result
- Java test coverage for daily: Hotspot 8,  OpenJDK11 or 8
- identify which guides to do manual tests for the GM candidate 
  - getting guide
  - gradle guide
  - open tracing
  - docker
  - ...

**Comment by gkwan-ibm** [comment]
- 2 wrong naming issues are not resolved
- OpenJDK11 test is running
   - P1: addressing several guides failures
   - P1: Kube guides failed on 9, 10, 11
- P1: each batch should run separately by a platform and a jdk version

**Comment by gkwan-ibm** [comment]
- test are running in 2 batches OracleJDK and OpenJDK
- works
  - gradle guide need to be fixed
  - OpenJDK11 failures 
  - MacOS

**Comment by evelinec** [comment]
- investigate the openjdk11 version used in travis test: 

Downloading JDK from https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by evelinec** [comment]
When GM build is declared, we need to manually test the following guides and platform combinations: 

Platform and JDK: 
- [ ] Linux + JDK8
- [ ] Linux + JDK11

Guides: 
- [ ] Gradle
- [ ] Kube-Intro
- [ ] Kube-Config
- [ ] Kube-Health

**Comment by evelinec** [comment]
- auto test didn't pick up GM driver.. need investigation

**Comment by gkwan-ibm** [comment]
- PR for Kube guides is ready but still need to be verified 
- need to clarify with Andy about the OL docker image build

**Comment by gkwan-ibm** [comment]
- last night run for kube guides, except used the latest docker image
  - docker image need to be tagged by build-level
  - make sure to remove docker image if tests are pass
- investigating the Metric and JWT test failures on past 2 days

**Comment by gkwan-ibm** [comment]
- kubes guides are running on daily build
- need to enable the Jenkin to run Istio guide (Andrew)

**Comment by gkwan-ibm** [comment]
- figured out the metric failure
  - PR is ready and approved
- investigating the JWT failure
- investigating other failures, e.g. opentracing, cdi, kube health, cors

**Comment by gkwan-ibm** [comment]
- metric failure not happen anymore
- investigating the JWT failure 
- figured out the Isito failure
- figured out other failures, e.g. install jdk failed

**Comment by gkwan-ibm** [comment]
- continue to investigate the JWT failure which should be related to SSL

**Comment by gkwan-ibm** [comment]
- JWT failure is still not resolved

**Comment by evelinec** [comment]
- 2 guides failed with Travis test error, re-run the tests are good

**Comment by evelinec** [comment]
Revisited the test coverage and daily build test enablements for the following guide, and opened the relevant issues: 

- docker
- getting started
- angularjs

These guides were examined but the current tests seem good: 
- gradle
- maven-intro
- JWT

**Comment by evelinec** [comment]
As discussed, the team wants to have the following documentation for the current automation infrastructure: 
- an overview 
- document the docker image tests, feature update, and draft guide tests

@gkwan-ibm and @andrewdes

**Comment by evelinec** [comment]
Looks like last night's massive daily build test failure is due to some connectivity issue with Maven Central Repository: https://www.traviscistatus.com/incidents/mm020jn4nzcn from Travis. Since this afternoon, some tests are able to run successfully.

**Comment by evelinec** [comment]
The above reported problem had been resolved. The daily build tests last night all ran successfully.

**Comment by gkwan-ibm** [comment]
close
- the test framework was migrated to use Github actions
