### ISSUE TITLE
Create guides for MP Reactive Messaging

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#27]
Create guides for MP Reactive Messaging and associated APIs.  Use Kafka as backend.

**Comment by yeekangc** [comment]
Need further input from @hughesj and we should consider how this relates to what is happening in this space in the MicroProfile community.

**Comment by gcharters** [comment]
@gcharters to investigate scope and re-raise once we know what we want to create.

**Comment by hutchig** [comment]
Compare with https://quarkus.io/guides/kafka-guide

**Comment by gcharters** [comment]
Yes, I think this should be covering Reactive Messaging?  Can we get it repurposed and prioritized appropriately?  @yeekangc Reactive Messaging seems to have fallen through that cracks along with Reactive Streams Operators.  We implement both of these in OL but they're not part of the MicroProfile platform (they're standalone specs).  I think they're important and we should have guides for them asap.  

@hughesj - wdyt?

**Comment by hughesj** [comment]
agreed - I have users wanting a worked example.

**Comment by yeekangc** [comment]
@gcharters, they are still priorities.  Then, we do need to sort out the various issues we have on the topic and update them (clean them up).

I have been thinking of re-purposing this for Reactive Messaging (or closing it in favour of others) too.

We have some Async guides out and we are certainly looking at Reactive Messaging and what we have in MP next.  Working on a Kafka one too.

@gkwan-ibm @ankitagrawa

**Comment by yeekangc** [comment]
I should also add that the team is trying to map out what we should have in this series (domain).  Will share that for feedback and file issues for them ASAP.

**Comment by hughesj** [comment]
hi @yeekangc the important thing here is a guide that demonstrates Reactive Messaging with Kafka. So, perhaps you could either rescope the details of this one - no akka required. Thanks.

**Comment by GraceJansen** [comment]
Would love to help out making this guide in the new year

**Comment by yeekangc** [comment]
Thanks, @GraceJansen!

@ankitagrawa is looking at what we should have and we will reach out.

**Comment by gkwan-ibm** [comment]
Plan:
- [ ] Prototype an application to use MP reactive messaging within a microservice
  - enhance the InventoryResource and InventoryManager
- [ ] Prototype an application to use MP reactive messaging among multiple microservices with Kafka
   - enhance the application in the draft-guide-jax-rs-reactive-client dev branch
- [ ] Outline the 3 guides
   - Talk about the basic of MP reactive messaging
   - Talk about using MP reactive messaging in multiple microservices with Kafka
   - Talk about Acknowledgement 
- [ ] Draft the guides
- [ ] Publish the guides

**Comment by matthewpwilson** [comment]
I have a few suggestions on some topics that could be included: 
- Creating a BFF type app that consumes messages from a Reactive Messaging channel and pushes them to a frontend application via SSE or Websockets
- Emitting messages to multiple channels
- De-duplicating messages
These are problems I had to solve when writing an app using reactive messaging and I found quite tricky! They are potentially more advanced issues though.

**Comment by gkwan-ibm** [comment]
Updated plan for MP Reactive Messaging guides:
- ~Create a guide to talk about MP Reactive Messaging within a microservice~
- [ ] (in progress) Create a guide to talk about MP Reactive Messaging among microservices with Kafka (https://draft-guides.mybluemix.net/guides/microprofile-reactive-messaging.html) 
```
git clone https://github.com/openliberty/draft-guide-microprofile-reactive-messaging.git -b dev
cd draft-guide-microprofile-reactive-messaging
```
- [ ] Create a guide to talk about Acknowledgement
- [ ] Create a guide to talk about implementing own Connector
- [ ] (considering) Create a guide to talk about testing MP Reactive Messaging microservice by using MST and Kakfa test container
- [ ]  Create a guide to talk about pushing messages to frontend application via SSE or Websockets

**Comment by ankitagrawa** [comment]
1) add travis to the draft guide.

**Comment by gkwan-ibm** [comment]
new plan:
- [x] reactive messaging
- [x] test reactive services
- [ ] trigger message by rest
- [ ] acknowledgement
- [ ] frontend SSE
- [ ] revise the async guide
- [ ] revise the reactive client guide

**Comment by yeekangc** [comment]
Completed all reactive guides that've been planned as part of this epic.
