### ISSUE TITLE
Accessibility support for the static guides

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#473]
- identify the accessibility test scope
  - https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html
    - AVT 1 = Automated testing
    - AVT 2 = Manual testing
      - a picture requires alternative text to describe the image
      - table requires alternative text
      - test color contrast
      - test using keyboard instead of mouse
      - ...
    - AVT 3 = Screen Reader testing
       - use JAWS screen reader
- AVT 1 for all guides (Tiago)
  - https://github.com/OpenLiberty/guides-common/issues/486 
- AVT 3 for all guides (Danny and Darren)
  - https://github.com/OpenLiberty/guides-common/issues/491
- select some guides to perform AVT 2 and 3:
  - getting-started (Tiago)
    - [x] https://github.com/OpenLiberty/guide-getting-started/issues/188
  - cors (Darren)
    - [x] https://github.com/OpenLiberty/guide-cors/issues/59
  - gradle (Danny)
    - [x] https://github.com/OpenLiberty/guide-gradle-intro/issues/74
  - kubernetes-intro
  - microprofile-reactive-messaging
  - cloud-ibm
  - reactjs
  - openshift-operator
  - opentracing-jaeger
- address any violation

**Comment by yeekangc** [comment]
@mbroz2 @chirp1
