### ISSUE TITLE
Daily Build Automation - not really test against the daily build

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#500]
- investigate which guides are not really verify against the daily build
  - the `sed -i...` command cannot add the `runtimeUrl`
  - the Dockerfile by searching `Step 1/7 : ` , should get
   - `Step 1/7 : FROM [secure]/olguides:cl201020200825-1100`
- Fix the following found guides which has this problem:
  - [ ] guide-arquillian-managed
  - [ ] guide-jpa-intro 
  - [ ] ...see below comment...

**Comment by MaiHameed** [comment]
**Task: Check Travis logs**

Check the Travis logs for the following guides to see if they are correctly testing the guide. Check if:
- The pom.xml files and Dockerfiles (if any) is correctly configured to use the nightly builds/images

Add a comment under the guide checkbox with either `Broken` or `Works`, put your name, and check off the box to showcase that it's been investigated.

Repo List:
- [ ] guide-microprofile-reactive-messaging-rest-integration
- [ ] guide-okd
- [ ] guide-arquillian-managed
- [ ] guide-microprofile-openapi
- [ ] guide-reactive-service-testing
- [ ] guide-microprofile-metrics
- [ ] guide-jpa-intro
- [ ] guide-microprofile-istio-retry-fallback
- [ ] guide-sessions
- [ ] guide-rest-client-angular
- [ ] guide-rest-client-reactjs
- [ ] guide-microprofile-opentracing
- [ ] guide-microprofile-opentracing-jaeger
- [ ] guide-kubernetes-intro
- [ ] guide-bean-validation
- [ ] guide-rest-client-angularjs
- [ ] guide-microshed-testing
- [ ] guide-maven-intro
- [ ] guide-kubernetes-microprofile-health
- [ ] guide-microprofile-rest-client
- [ ] guide-spring-boot
- [ ] guide-security-intro
- [ ] guide-rest-intro
- [ ] guide-microprofile-reactive-messaging
- [ ] guide-microprofile-jwt
- [ ] guide-kubernetes-microprofile-config
- [ ] guide-gradle-intro
- [ ] guide-docker
- [ ] guide-cloud-ibm
- [ ] guide-cors
- [ ] guide-containerize
- [ ] guide-microprofile-config
- [ ] guide-rest-client-java
- [ ] guide-microprofile-fallback
- [ ] guide-cloud-azure
- [ ] guide-cdi-intro
- [ ] guide-microprofile-health
- [ ] guide-cloud-aws
- [ ] guide-istio-intro
- [ ] guide-cloud-google
- [ ] guide-cloud-openshift
- [ ] guide-microprofile-rest-client-async
- [ ] guide-maven-multimodules
- [ ] guide-rest-hateoas
- [ ] guide-getting-started
