### ISSUE TITLE
Consider to use kernel-slim image

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#861]
Use kernel-slim image as https://github.com/OpenLiberty/ci.docker#building-an-application-image and remove the docker pull command for the following guides, if they do not impact the performance, such as devc mode or MST:

- [ ] guide-liberty-deep-dive
- [ ] guide-cloud-openshift-operator
- [ ] guide-sessions
- [ ] guide-microprofile-graphql
- [ ] guide-graphql-client
- [ ] guide-getting-started
- [ ] guide-openliberty-operator-openshift
- [ ] guide-microprofile-reactive-messaging-acknowledgment
- [ ] guide-reactive-rest-client
- [ ] guide-microprofile-reactive-messaging-rest-integration
- [ ] guide-openliberty-operator-intro
- [ ] guide-containerize
- [ ] guide-microprofile-reactive-messaging
- [ ] guide-cloud-ibm
- [ ] guide-kubernetes-intro
- [ ] guide-kubernetes-microprofile-config
- [ ] guide-microprofile-rest-client-async
- [ ] guide-openshift-codeready-containers
- [ ] guide-reactive-messaging-sse
- [ ] guide-cloud-aws
- [ ] guide-docker
- [ ] guide-istio-intro
- [ ] guide-reactive-service-testing
- [ ] guide-microprofile-istio-retry-fallback
- [ ] guide-liberty-deep-dive-gradle
- [ ] guide-kubernetes-microprofile-health
- [ ] guide-spring-boot
- [ ] guide-cloud-azure
- [ ] guide-containerize-podman
- [ ] guide-liberty-deep-dive-gradle

Note: in the Dockerfile, also need to run features.sh

**Comment by gkwan-ibm** [comment]
close
- all guides were updated except liberty-deep-dive, liberty-deep-dive-gradle, and spring-boot
